-- Production constraints and non-constraint indexes snapshot; generated 2026-09-22.
-- DATA-FREE. Ordered so keys/checks exist before foreign keys.

ALTER TABLE public.academic_years ADD CONSTRAINT academic_years_pkey PRIMARY KEY (id);
ALTER TABLE public.academic_years ADD CONSTRAINT academic_years_school_id_name_key UNIQUE (school_id, name);
ALTER TABLE public.ai_action_logs ADD CONSTRAINT ai_action_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_agents ADD CONSTRAINT ai_agents_organization_id_slug_key UNIQUE (organization_id, slug);
ALTER TABLE public.ai_agents ADD CONSTRAINT ai_agents_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_conversations ADD CONSTRAINT ai_conversations_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_execution_runs ADD CONSTRAINT ai_execution_runs_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_execution_runs ADD CONSTRAINT ai_execution_runs_school_id_idempotency_key_key UNIQUE (school_id, idempotency_key);
ALTER TABLE public.ai_execution_runs ADD CONSTRAINT ai_execution_runs_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'awaiting_confirmation'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'cancelled'::text])));
ALTER TABLE public.ai_execution_steps ADD CONSTRAINT ai_execution_steps_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_execution_steps ADD CONSTRAINT ai_execution_steps_risk_level_check CHECK ((risk_level = ANY (ARRAY['read'::text, 'write'::text, 'external'::text])));
ALTER TABLE public.ai_execution_steps ADD CONSTRAINT ai_execution_steps_run_id_step_order_key UNIQUE (run_id, step_order);
ALTER TABLE public.ai_execution_steps ADD CONSTRAINT ai_execution_steps_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'awaiting_confirmation'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'skipped'::text])));
ALTER TABLE public.ai_execution_steps ADD CONSTRAINT ai_execution_steps_step_order_check CHECK ((step_order > 0));
ALTER TABLE public.ai_messages ADD CONSTRAINT ai_messages_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_tool_permissions ADD CONSTRAINT ai_tool_permissions_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_tool_permissions ADD CONSTRAINT ai_tool_permissions_tool_id_role_id_key UNIQUE (tool_id, role_id);
ALTER TABLE public.ai_tools ADD CONSTRAINT ai_tools_organization_id_slug_key UNIQUE (organization_id, slug);
ALTER TABLE public.ai_tools ADD CONSTRAINT ai_tools_pkey PRIMARY KEY (id);
ALTER TABLE public.ai_tools ADD CONSTRAINT ai_tools_risk_level_check CHECK ((risk_level = ANY (ARRAY['read'::text, 'write'::text, 'external'::text])));
ALTER TABLE public.attendance_records ADD CONSTRAINT attendance_records_pkey PRIMARY KEY (id);
ALTER TABLE public.attendance_records ADD CONSTRAINT attendance_records_session_id_enrollment_id_key UNIQUE (session_id, enrollment_id);
ALTER TABLE public.attendance_records ADD CONSTRAINT attendance_records_status_check CHECK ((status = ANY (ARRAY['present'::text, 'absent'::text, 'late'::text, 'excused'::text])));
ALTER TABLE public.attendance_sessions ADD CONSTRAINT attendance_sessions_pkey PRIMARY KEY (id);
ALTER TABLE public.attendance_sessions ADD CONSTRAINT attendance_sessions_school_id_academic_year_id_section_id_a_key UNIQUE (school_id, academic_year_id, section_id, attendance_date);
ALTER TABLE public.attendance_sessions ADD CONSTRAINT attendance_sessions_status_check CHECK ((status = ANY (ARRAY['open'::text, 'submitted'::text, 'locked'::text])));
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);
ALTER TABLE public.communication_campaigns ADD CONSTRAINT communication_campaigns_audience_type_check CHECK ((audience_type = ANY (ARRAY['all_guardians'::text, 'student_guardians'::text, 'staff'::text, 'all_school'::text])));
ALTER TABLE public.communication_campaigns ADD CONSTRAINT communication_campaigns_body_check CHECK (((length(btrim(body)) >= 1) AND (length(btrim(body)) <= 10000)));
ALTER TABLE public.communication_campaigns ADD CONSTRAINT communication_campaigns_channel_check CHECK ((channel = ANY (ARRAY['in_app'::text, 'email'::text, 'sms'::text, 'whatsapp'::text])));
ALTER TABLE public.communication_campaigns ADD CONSTRAINT communication_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE public.communication_campaigns ADD CONSTRAINT communication_campaigns_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'sent'::text, 'cancelled'::text])));
ALTER TABLE public.communication_campaigns ADD CONSTRAINT communication_campaigns_title_check CHECK (((length(btrim(title)) >= 3) AND (length(btrim(title)) <= 200)));
ALTER TABLE public.communication_recipients ADD CONSTRAINT communication_recipients_campaign_id_guardian_id_staff_id_key UNIQUE (campaign_id, guardian_id, staff_id);
ALTER TABLE public.communication_recipients ADD CONSTRAINT communication_recipients_check CHECK (((((guardian_id IS NOT NULL))::integer + ((staff_id IS NOT NULL))::integer) = 1));
ALTER TABLE public.communication_recipients ADD CONSTRAINT communication_recipients_delivery_status_check CHECK ((delivery_status = ANY (ARRAY['queued'::text, 'sent'::text, 'delivered'::text, 'failed'::text, 'read'::text])));
ALTER TABLE public.communication_recipients ADD CONSTRAINT communication_recipients_pkey PRIMARY KEY (id);
ALTER TABLE public.curriculum_units ADD CONSTRAINT curriculum_units_grade_id_subject_id_sequence_no_key UNIQUE (grade_id, subject_id, sequence_no);
ALTER TABLE public.curriculum_units ADD CONSTRAINT curriculum_units_pkey PRIMARY KEY (id);
ALTER TABLE public.exam_results ADD CONSTRAINT exam_results_exam_subject_id_enrollment_id_key UNIQUE (exam_subject_id, enrollment_id);
ALTER TABLE public.exam_results ADD CONSTRAINT exam_results_marks_check CHECK ((marks >= (0)::numeric));
ALTER TABLE public.exam_results ADD CONSTRAINT exam_results_pkey PRIMARY KEY (id);
ALTER TABLE public.exam_subjects ADD CONSTRAINT exam_subjects_check CHECK ((pass_marks <= max_marks));
ALTER TABLE public.exam_subjects ADD CONSTRAINT exam_subjects_exam_id_subject_id_key UNIQUE (exam_id, subject_id);
ALTER TABLE public.exam_subjects ADD CONSTRAINT exam_subjects_marks_check CHECK (((max_marks > (0)::numeric) AND (pass_marks >= (0)::numeric) AND (pass_marks <= max_marks)));
ALTER TABLE public.exam_subjects ADD CONSTRAINT exam_subjects_max_marks_check CHECK ((max_marks > (0)::numeric));
ALTER TABLE public.exam_subjects ADD CONSTRAINT exam_subjects_pass_marks_check CHECK ((pass_marks >= (0)::numeric));
ALTER TABLE public.exam_subjects ADD CONSTRAINT exam_subjects_pkey PRIMARY KEY (id);
ALTER TABLE public.exams ADD CONSTRAINT exams_dates_check CHECK (((end_date IS NULL) OR (start_date IS NULL) OR (end_date >= start_date)));
ALTER TABLE public.exams ADD CONSTRAINT exams_exam_type_check CHECK ((exam_type = ANY (ARRAY['unit'::text, 'midterm'::text, 'term'::text, 'final'::text, 'assessment'::text, 'other'::text])));
ALTER TABLE public.exams ADD CONSTRAINT exams_max_marks_check CHECK ((max_marks > (0)::numeric));
ALTER TABLE public.exams ADD CONSTRAINT exams_pkey PRIMARY KEY (id);
ALTER TABLE public.exams ADD CONSTRAINT exams_school_id_academic_year_id_name_key UNIQUE (school_id, academic_year_id, name);
ALTER TABLE public.exams ADD CONSTRAINT exams_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'published'::text, 'locked'::text])));
ALTER TABLE public.fee_invoice_items ADD CONSTRAINT fee_invoice_items_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.fee_invoice_items ADD CONSTRAINT fee_invoice_items_check CHECK (((discount >= (0)::numeric) AND (discount <= amount)));
ALTER TABLE public.fee_invoice_items ADD CONSTRAINT fee_invoice_items_pkey PRIMARY KEY (id);
ALTER TABLE public.fee_invoices ADD CONSTRAINT fee_invoices_check CHECK (((discount >= (0)::numeric) AND (discount <= subtotal)));
ALTER TABLE public.fee_invoices ADD CONSTRAINT fee_invoices_pkey PRIMARY KEY (id);
ALTER TABLE public.fee_invoices ADD CONSTRAINT fee_invoices_school_id_invoice_number_key UNIQUE (school_id, invoice_number);
ALTER TABLE public.fee_invoices ADD CONSTRAINT fee_invoices_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'issued'::text, 'partially_paid'::text, 'paid'::text, 'overdue'::text, 'cancelled'::text])));
ALTER TABLE public.fee_invoices ADD CONSTRAINT fee_invoices_subtotal_check CHECK ((subtotal >= (0)::numeric));
ALTER TABLE public.fee_payments ADD CONSTRAINT fee_payments_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.fee_payments ADD CONSTRAINT fee_payments_payment_method_check CHECK ((payment_method = ANY (ARRAY['cash'::text, 'card'::text, 'bank_transfer'::text, 'upi'::text, 'cheque'::text, 'online'::text, 'other'::text])));
ALTER TABLE public.fee_payments ADD CONSTRAINT fee_payments_pkey PRIMARY KEY (id);
ALTER TABLE public.fee_payments ADD CONSTRAINT fee_payments_school_id_receipt_number_key UNIQUE (school_id, receipt_number);
ALTER TABLE public.fee_payments ADD CONSTRAINT fee_payments_status_check CHECK ((status = ANY (ARRAY['completed'::text, 'reversed'::text])));
ALTER TABLE public.fee_structures ADD CONSTRAINT fee_structures_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.fee_structures ADD CONSTRAINT fee_structures_due_day_check CHECK (((due_day IS NULL) OR ((due_day >= 1) AND (due_day <= 28))));
ALTER TABLE public.fee_structures ADD CONSTRAINT fee_structures_fee_type_check CHECK ((fee_type = ANY (ARRAY['tuition'::text, 'admission'::text, 'transport'::text, 'hostel'::text, 'library'::text, 'exam'::text, 'activity'::text, 'other'::text])));
ALTER TABLE public.fee_structures ADD CONSTRAINT fee_structures_frequency_check CHECK ((frequency = ANY (ARRAY['one_time'::text, 'monthly'::text, 'quarterly'::text, 'term'::text, 'annual'::text])));
ALTER TABLE public.fee_structures ADD CONSTRAINT fee_structures_pkey PRIMARY KEY (id);
ALTER TABLE public.fee_structures ADD CONSTRAINT fee_structures_school_id_academic_year_id_name_grade_id_key UNIQUE (school_id, academic_year_id, name, grade_id);
ALTER TABLE public.grades ADD CONSTRAINT grades_pkey PRIMARY KEY (id);
ALTER TABLE public.grades ADD CONSTRAINT grades_school_id_name_key UNIQUE (school_id, name);
ALTER TABLE public.guardians ADD CONSTRAINT guardians_pkey PRIMARY KEY (id);
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_committed_rows_check CHECK ((committed_rows >= 0));
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_invalid_rows_check CHECK ((invalid_rows >= 0));
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_pkey PRIMARY KEY (id);
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_skipped_rows_check CHECK ((skipped_rows >= 0));
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_source_type_check CHECK ((source_type = ANY (ARRAY['xlsx'::text, 'csv'::text, 'json'::text])));
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_status_check CHECK ((status = ANY (ARRAY['staged'::text, 'validated'::text, 'ready'::text, 'committed'::text, 'failed'::text, 'cancelled'::text])));
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_total_rows_check CHECK ((total_rows >= 0));
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_valid_rows_check CHECK ((valid_rows >= 0));
ALTER TABLE public.import_rows ADD CONSTRAINT import_rows_batch_id_row_number_key UNIQUE (batch_id, row_number);
ALTER TABLE public.import_rows ADD CONSTRAINT import_rows_pkey PRIMARY KEY (id);
ALTER TABLE public.import_rows ADD CONSTRAINT import_rows_row_number_check CHECK ((row_number > 0));
ALTER TABLE public.import_rows ADD CONSTRAINT import_rows_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'valid'::text, 'invalid'::text, 'skipped'::text, 'imported'::text])));
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_dates_check CHECK ((end_date >= start_date));
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_days_check CHECK ((days > (0)::numeric));
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_pkey PRIMARY KEY (id);
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text])));
ALTER TABLE public.leave_types ADD CONSTRAINT leave_type_code_unique UNIQUE (school_id, code);
ALTER TABLE public.leave_types ADD CONSTRAINT leave_type_limit_check CHECK (((annual_limit IS NULL) OR (annual_limit >= (0)::numeric)));
ALTER TABLE public.leave_types ADD CONSTRAINT leave_types_pkey PRIMARY KEY (id);
ALTER TABLE public.lessons ADD CONSTRAINT lessons_pkey PRIMARY KEY (id);
ALTER TABLE public.lessons ADD CONSTRAINT lessons_status_check CHECK ((status = ANY (ARRAY['planned'::text, 'in_progress'::text, 'completed'::text])));
ALTER TABLE public.notification_preferences ADD CONSTRAINT notification_preferences_pkey PRIMARY KEY (user_id, school_id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_body_check CHECK ((btrim(body) <> ''::text));
ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE public.notifications ADD CONSTRAINT notifications_title_check CHECK ((btrim(title) <> ''::text));
ALTER TABLE public.organization_memberships ADD CONSTRAINT organization_memberships_organization_id_user_id_key UNIQUE (organization_id, user_id);
ALTER TABLE public.organization_memberships ADD CONSTRAINT organization_memberships_pkey PRIMARY KEY (id);
ALTER TABLE public.organizations ADD CONSTRAINT organizations_billing_status_check CHECK ((billing_status = ANY (ARRAY['trialing'::text, 'active'::text, 'past_due'::text, 'paused'::text, 'canceled'::text])));
ALTER TABLE public.organizations ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);
ALTER TABLE public.organizations ADD CONSTRAINT organizations_plan_check CHECK ((plan = ANY (ARRAY['starter'::text, 'growth'::text, 'pro'::text, 'enterprise'::text])));
ALTER TABLE public.organizations ADD CONSTRAINT organizations_slug_key UNIQUE (slug);
ALTER TABLE public.permissions ADD CONSTRAINT permissions_key_key UNIQUE (key);
ALTER TABLE public.permissions ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);
ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id);
ALTER TABLE public.roles ADD CONSTRAINT roles_key_key UNIQUE (key);
ALTER TABLE public.roles ADD CONSTRAINT roles_pkey PRIMARY KEY (id);
ALTER TABLE public.roles ADD CONSTRAINT roles_scope_check CHECK ((scope = ANY (ARRAY['platform'::text, 'organization'::text, 'school'::text])));
ALTER TABLE public.school_database_provisioning ADD CONSTRAINT school_database_provisioning_database_key_key UNIQUE (database_key);
ALTER TABLE public.school_database_provisioning ADD CONSTRAINT school_database_provisioning_database_mode_check CHECK ((database_mode = 'dedicated_project'::text));
ALTER TABLE public.school_database_provisioning ADD CONSTRAINT school_database_provisioning_pkey PRIMARY KEY (id);
ALTER TABLE public.school_database_provisioning ADD CONSTRAINT school_database_provisioning_school_id_key UNIQUE (school_id);
ALTER TABLE public.school_database_provisioning ADD CONSTRAINT school_database_provisioning_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'provisioning'::text, 'ready'::text, 'failed'::text])));
ALTER TABLE public.school_memberships ADD CONSTRAINT school_memberships_pkey PRIMARY KEY (id);
ALTER TABLE public.school_memberships ADD CONSTRAINT school_memberships_school_id_user_id_key UNIQUE (school_id, user_id);
ALTER TABLE public.school_onboarding_profiles ADD CONSTRAINT school_onboarding_profiles_current_step_check CHECK (((current_step >= 1) AND (current_step <= 8)));
ALTER TABLE public.school_onboarding_profiles ADD CONSTRAINT school_onboarding_profiles_pkey PRIMARY KEY (id);
ALTER TABLE public.school_onboarding_profiles ADD CONSTRAINT school_onboarding_profiles_school_id_key UNIQUE (school_id);
ALTER TABLE public.school_onboarding_profiles ADD CONSTRAINT school_onboarding_profiles_status_check CHECK ((status = ANY (ARRAY['in_progress'::text, 'completed'::text])));
ALTER TABLE public.schools ADD CONSTRAINT schools_organization_id_code_key UNIQUE (organization_id, code);
ALTER TABLE public.schools ADD CONSTRAINT schools_pkey PRIMARY KEY (id);
ALTER TABLE public.sections ADD CONSTRAINT sections_pkey PRIMARY KEY (id);
ALTER TABLE public.sections ADD CONSTRAINT sections_school_id_grade_id_name_key UNIQUE (school_id, grade_id, name);
ALTER TABLE public.staff_members ADD CONSTRAINT staff_employee_number_unique UNIQUE (school_id, employee_number);
ALTER TABLE public.staff_members ADD CONSTRAINT staff_employment_type_check CHECK ((employment_type = ANY (ARRAY['full_time'::text, 'part_time'::text, 'contract'::text, 'temporary'::text, 'intern'::text])));
ALTER TABLE public.staff_members ADD CONSTRAINT staff_members_pkey PRIMARY KEY (id);
ALTER TABLE public.staff_members ADD CONSTRAINT staff_salary_check CHECK (((salary IS NULL) OR (salary >= (0)::numeric)));
ALTER TABLE public.staff_members ADD CONSTRAINT staff_status_check CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text, 'on_leave'::text, 'terminated'::text])));
ALTER TABLE public.student_enrollments ADD CONSTRAINT student_enrollments_pkey PRIMARY KEY (id);
ALTER TABLE public.student_enrollments ADD CONSTRAINT student_enrollments_student_id_academic_year_id_key UNIQUE (student_id, academic_year_id);
ALTER TABLE public.student_fee_assignments ADD CONSTRAINT student_fee_assignments_amount_check CHECK ((amount > (0)::numeric));
ALTER TABLE public.student_fee_assignments ADD CONSTRAINT student_fee_assignments_check CHECK (((discount >= (0)::numeric) AND (discount <= amount)));
ALTER TABLE public.student_fee_assignments ADD CONSTRAINT student_fee_assignments_enrollment_id_fee_structure_id_key UNIQUE (enrollment_id, fee_structure_id);
ALTER TABLE public.student_fee_assignments ADD CONSTRAINT student_fee_assignments_pkey PRIMARY KEY (id);
ALTER TABLE public.student_fee_assignments ADD CONSTRAINT student_fee_assignments_status_check CHECK ((status = ANY (ARRAY['active'::text, 'waived'::text, 'cancelled'::text])));
ALTER TABLE public.student_guardians ADD CONSTRAINT student_guardians_pkey PRIMARY KEY (student_id, guardian_id);
ALTER TABLE public.students ADD CONSTRAINT students_pkey PRIMARY KEY (id);
ALTER TABLE public.students ADD CONSTRAINT students_school_id_admission_number_key UNIQUE (school_id, admission_number);
ALTER TABLE public.subjects ADD CONSTRAINT subjects_pkey PRIMARY KEY (id);
ALTER TABLE public.subjects ADD CONSTRAINT subjects_school_id_code_key UNIQUE (school_id, code);
ALTER TABLE public.subjects ADD CONSTRAINT subjects_school_id_name_key UNIQUE (school_id, name);
ALTER TABLE public.timetable_entries ADD CONSTRAINT timetable_entries_day_of_week_check CHECK (((day_of_week >= 1) AND (day_of_week <= 7)));
ALTER TABLE public.timetable_entries ADD CONSTRAINT timetable_entries_period_no_check CHECK ((period_no > 0));
ALTER TABLE public.timetable_entries ADD CONSTRAINT timetable_entries_pkey PRIMARY KEY (id);
ALTER TABLE public.timetable_entries ADD CONSTRAINT timetable_entries_section_id_day_of_week_period_no_key UNIQUE (section_id, day_of_week, period_no);
ALTER TABLE public.user_profiles ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_scope_consistency CHECK ((((organization_id IS NOT NULL) AND (school_id IS NULL)) OR ((organization_id IS NULL) AND (school_id IS NOT NULL)) OR ((organization_id IS NULL) AND (school_id IS NULL))));
ALTER TABLE public.academic_years ADD CONSTRAINT academic_years_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.ai_action_logs ADD CONSTRAINT ai_action_logs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES ai_agents(id) ON DELETE SET NULL;
ALTER TABLE public.ai_action_logs ADD CONSTRAINT ai_action_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.ai_action_logs ADD CONSTRAINT ai_action_logs_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL;
ALTER TABLE public.ai_action_logs ADD CONSTRAINT ai_action_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.ai_agents ADD CONSTRAINT ai_agents_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.ai_conversations ADD CONSTRAINT ai_conversations_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES ai_agents(id) ON DELETE SET NULL;
ALTER TABLE public.ai_conversations ADD CONSTRAINT ai_conversations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.ai_conversations ADD CONSTRAINT ai_conversations_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.ai_conversations ADD CONSTRAINT ai_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.ai_execution_runs ADD CONSTRAINT ai_execution_runs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id);
ALTER TABLE public.ai_execution_runs ADD CONSTRAINT ai_execution_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id);
ALTER TABLE public.ai_execution_runs ADD CONSTRAINT ai_execution_runs_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id);
ALTER TABLE public.ai_execution_runs ADD CONSTRAINT ai_execution_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
ALTER TABLE public.ai_execution_steps ADD CONSTRAINT ai_execution_steps_run_id_fkey FOREIGN KEY (run_id) REFERENCES ai_execution_runs(id) ON DELETE CASCADE;
ALTER TABLE public.ai_messages ADD CONSTRAINT ai_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE;
ALTER TABLE public.ai_tool_permissions ADD CONSTRAINT ai_tool_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE public.ai_tool_permissions ADD CONSTRAINT ai_tool_permissions_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES ai_tools(id) ON DELETE CASCADE;
ALTER TABLE public.ai_tools ADD CONSTRAINT ai_tools_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.attendance_records ADD CONSTRAINT attendance_records_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES student_enrollments(id) ON DELETE RESTRICT;
ALTER TABLE public.attendance_records ADD CONSTRAINT attendance_records_marked_by_fkey FOREIGN KEY (marked_by) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.attendance_records ADD CONSTRAINT attendance_records_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.attendance_records ADD CONSTRAINT attendance_records_session_id_fkey FOREIGN KEY (session_id) REFERENCES attendance_sessions(id) ON DELETE CASCADE;
ALTER TABLE public.attendance_records ADD CONSTRAINT attendance_records_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE RESTRICT;
ALTER TABLE public.attendance_sessions ADD CONSTRAINT attendance_sessions_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE RESTRICT;
ALTER TABLE public.attendance_sessions ADD CONSTRAINT attendance_sessions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.attendance_sessions ADD CONSTRAINT attendance_sessions_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.attendance_sessions ADD CONSTRAINT attendance_sessions_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE RESTRICT;
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL;
ALTER TABLE public.audit_logs ADD CONSTRAINT audit_logs_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL;
ALTER TABLE public.communication_campaigns ADD CONSTRAINT communication_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.communication_campaigns ADD CONSTRAINT communication_campaigns_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.communication_recipients ADD CONSTRAINT communication_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES communication_campaigns(id) ON DELETE CASCADE;
ALTER TABLE public.communication_recipients ADD CONSTRAINT communication_recipients_guardian_id_fkey FOREIGN KEY (guardian_id) REFERENCES guardians(id) ON DELETE CASCADE;
ALTER TABLE public.communication_recipients ADD CONSTRAINT communication_recipients_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES staff_members(id) ON DELETE CASCADE;
ALTER TABLE public.curriculum_units ADD CONSTRAINT curriculum_units_grade_id_fkey FOREIGN KEY (grade_id) REFERENCES grades(id) ON DELETE CASCADE;
ALTER TABLE public.curriculum_units ADD CONSTRAINT curriculum_units_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.curriculum_units ADD CONSTRAINT curriculum_units_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE;
ALTER TABLE public.exam_results ADD CONSTRAINT exam_results_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES student_enrollments(id) ON DELETE RESTRICT;
ALTER TABLE public.exam_results ADD CONSTRAINT exam_results_entered_by_fkey FOREIGN KEY (entered_by) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.exam_results ADD CONSTRAINT exam_results_exam_subject_id_fkey FOREIGN KEY (exam_subject_id) REFERENCES exam_subjects(id) ON DELETE CASCADE;
ALTER TABLE public.exam_results ADD CONSTRAINT exam_results_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.exam_subjects ADD CONSTRAINT exam_subjects_exam_id_fkey FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE;
ALTER TABLE public.exam_subjects ADD CONSTRAINT exam_subjects_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.exam_subjects ADD CONSTRAINT exam_subjects_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE RESTRICT;
ALTER TABLE public.exams ADD CONSTRAINT exams_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE RESTRICT;
ALTER TABLE public.exams ADD CONSTRAINT exams_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.exams ADD CONSTRAINT exams_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.fee_invoice_items ADD CONSTRAINT fee_invoice_items_fee_structure_id_fkey FOREIGN KEY (fee_structure_id) REFERENCES fee_structures(id) ON DELETE SET NULL;
ALTER TABLE public.fee_invoice_items ADD CONSTRAINT fee_invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES fee_invoices(id) ON DELETE CASCADE;
ALTER TABLE public.fee_invoice_items ADD CONSTRAINT fee_invoice_items_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.fee_invoices ADD CONSTRAINT fee_invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.fee_invoices ADD CONSTRAINT fee_invoices_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES student_enrollments(id) ON DELETE RESTRICT;
ALTER TABLE public.fee_invoices ADD CONSTRAINT fee_invoices_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.fee_payments ADD CONSTRAINT fee_payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES fee_invoices(id) ON DELETE RESTRICT;
ALTER TABLE public.fee_payments ADD CONSTRAINT fee_payments_received_by_fkey FOREIGN KEY (received_by) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.fee_payments ADD CONSTRAINT fee_payments_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.fee_structures ADD CONSTRAINT fee_structures_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE RESTRICT;
ALTER TABLE public.fee_structures ADD CONSTRAINT fee_structures_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.fee_structures ADD CONSTRAINT fee_structures_grade_id_fkey FOREIGN KEY (grade_id) REFERENCES grades(id) ON DELETE SET NULL;
ALTER TABLE public.fee_structures ADD CONSTRAINT fee_structures_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.grades ADD CONSTRAINT grades_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.guardians ADD CONSTRAINT guardians_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.guardians ADD CONSTRAINT guardians_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES academic_years(id);
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public.import_batches ADD CONSTRAINT import_batches_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.import_rows ADD CONSTRAINT import_rows_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES import_batches(id) ON DELETE CASCADE;
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_leave_type_id_fkey FOREIGN KEY (leave_type_id) REFERENCES leave_types(id) ON DELETE RESTRICT;
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.leave_requests ADD CONSTRAINT leave_requests_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES staff_members(id) ON DELETE CASCADE;
ALTER TABLE public.leave_types ADD CONSTRAINT leave_types_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.lessons ADD CONSTRAINT lessons_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.lessons ADD CONSTRAINT lessons_curriculum_unit_id_fkey FOREIGN KEY (curriculum_unit_id) REFERENCES curriculum_units(id) ON DELETE SET NULL;
ALTER TABLE public.lessons ADD CONSTRAINT lessons_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.lessons ADD CONSTRAINT lessons_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE;
ALTER TABLE public.lessons ADD CONSTRAINT lessons_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE;
ALTER TABLE public.notification_preferences ADD CONSTRAINT notification_preferences_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.notification_preferences ADD CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.organization_memberships ADD CONSTRAINT organization_memberships_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.organization_memberships ADD CONSTRAINT organization_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE;
ALTER TABLE public.role_permissions ADD CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE public.school_database_provisioning ADD CONSTRAINT school_database_provisioning_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.school_database_provisioning ADD CONSTRAINT school_database_provisioning_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.school_memberships ADD CONSTRAINT school_memberships_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.school_memberships ADD CONSTRAINT school_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.school_onboarding_profiles ADD CONSTRAINT school_onboarding_profiles_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.schools ADD CONSTRAINT schools_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.sections ADD CONSTRAINT sections_grade_id_fkey FOREIGN KEY (grade_id) REFERENCES grades(id) ON DELETE CASCADE;
ALTER TABLE public.sections ADD CONSTRAINT sections_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.staff_members ADD CONSTRAINT staff_members_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.student_enrollments ADD CONSTRAINT student_enrollments_academic_year_id_fkey FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE RESTRICT;
ALTER TABLE public.student_enrollments ADD CONSTRAINT student_enrollments_grade_id_fkey FOREIGN KEY (grade_id) REFERENCES grades(id) ON DELETE RESTRICT;
ALTER TABLE public.student_enrollments ADD CONSTRAINT student_enrollments_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.student_enrollments ADD CONSTRAINT student_enrollments_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE SET NULL;
ALTER TABLE public.student_enrollments ADD CONSTRAINT student_enrollments_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
ALTER TABLE public.student_fee_assignments ADD CONSTRAINT student_fee_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.student_fee_assignments ADD CONSTRAINT student_fee_assignments_enrollment_id_fkey FOREIGN KEY (enrollment_id) REFERENCES student_enrollments(id) ON DELETE CASCADE;
ALTER TABLE public.student_fee_assignments ADD CONSTRAINT student_fee_assignments_fee_structure_id_fkey FOREIGN KEY (fee_structure_id) REFERENCES fee_structures(id) ON DELETE RESTRICT;
ALTER TABLE public.student_fee_assignments ADD CONSTRAINT student_fee_assignments_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.student_guardians ADD CONSTRAINT student_guardians_guardian_id_fkey FOREIGN KEY (guardian_id) REFERENCES guardians(id) ON DELETE CASCADE;
ALTER TABLE public.student_guardians ADD CONSTRAINT student_guardians_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
ALTER TABLE public.students ADD CONSTRAINT students_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.subjects ADD CONSTRAINT subjects_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.timetable_entries ADD CONSTRAINT timetable_entries_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.timetable_entries ADD CONSTRAINT timetable_entries_section_id_fkey FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE CASCADE;
ALTER TABLE public.timetable_entries ADD CONSTRAINT timetable_entries_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE;
ALTER TABLE public.timetable_entries ADD CONSTRAINT timetable_entries_teacher_user_id_fkey FOREIGN KEY (teacher_user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public.user_profiles ADD CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX ai_execution_runs_school_created_idx ON public.ai_execution_runs USING btree (school_id, created_at DESC);
CREATE INDEX ai_execution_runs_user_idx ON public.ai_execution_runs USING btree (user_id, created_at DESC);
CREATE INDEX ai_execution_steps_run_idx ON public.ai_execution_steps USING btree (run_id, step_order);
CREATE INDEX ai_tool_permissions_role_idx ON public.ai_tool_permissions USING btree (role_id);
CREATE INDEX ai_tools_org_active_idx ON public.ai_tools USING btree (organization_id, is_active);
CREATE INDEX attendance_records_session_idx ON public.attendance_records USING btree (session_id);
CREATE INDEX attendance_records_student_date_idx ON public.attendance_records USING btree (student_id, marked_at DESC);
CREATE INDEX attendance_sessions_school_date_idx ON public.attendance_sessions USING btree (school_id, attendance_date DESC);
CREATE INDEX attendance_sessions_section_date_idx ON public.attendance_sessions USING btree (section_id, attendance_date DESC);
CREATE INDEX communication_campaigns_school_created_idx ON public.communication_campaigns USING btree (school_id, created_at DESC);
CREATE INDEX communication_recipients_campaign_idx ON public.communication_recipients USING btree (campaign_id);
CREATE INDEX communication_recipients_guardian_idx ON public.communication_recipients USING btree (guardian_id) WHERE (guardian_id IS NOT NULL);
CREATE INDEX communication_recipients_staff_idx ON public.communication_recipients USING btree (staff_id) WHERE (staff_id IS NOT NULL);
CREATE INDEX fee_invoice_items_invoice_idx ON public.fee_invoice_items USING btree (invoice_id);
CREATE INDEX fee_invoices_school_status_due_idx ON public.fee_invoices USING btree (school_id, status, due_date);
CREATE INDEX fee_payments_invoice_idx ON public.fee_payments USING btree (invoice_id);
CREATE INDEX fee_payments_school_date_idx ON public.fee_payments USING btree (school_id, payment_date);
CREATE INDEX fee_structures_school_year_idx ON public.fee_structures USING btree (school_id, academic_year_id);
CREATE INDEX idx_ai_action_logs_agent ON public.ai_action_logs USING btree (agent_id);
CREATE INDEX idx_ai_action_logs_org ON public.ai_action_logs USING btree (organization_id);
CREATE INDEX idx_ai_action_logs_school ON public.ai_action_logs USING btree (school_id);
CREATE INDEX idx_ai_action_logs_user ON public.ai_action_logs USING btree (user_id);
CREATE INDEX idx_ai_conversations_agent ON public.ai_conversations USING btree (agent_id);
CREATE INDEX idx_ai_conversations_org ON public.ai_conversations USING btree (organization_id);
CREATE INDEX idx_ai_conversations_school ON public.ai_conversations USING btree (school_id);
CREATE INDEX idx_ai_conversations_user ON public.ai_conversations USING btree (user_id, created_at DESC);
CREATE INDEX idx_ai_messages_conversation ON public.ai_messages USING btree (conversation_id, created_at);
CREATE INDEX idx_audit_logs_actor ON public.audit_logs USING btree (actor_user_id);
CREATE INDEX idx_audit_logs_org ON public.audit_logs USING btree (organization_id);
CREATE INDEX idx_audit_school_created ON public.audit_logs USING btree (school_id, created_at DESC);
CREATE INDEX idx_curriculum_units_school_grade ON public.curriculum_units USING btree (school_id, grade_id);
CREATE INDEX idx_enrollments_grade ON public.student_enrollments USING btree (grade_id);
CREATE INDEX idx_enrollments_school_year ON public.student_enrollments USING btree (school_id, academic_year_id);
CREATE INDEX idx_enrollments_section ON public.student_enrollments USING btree (section_id);
CREATE INDEX idx_enrollments_year ON public.student_enrollments USING btree (academic_year_id);
CREATE INDEX idx_exam_results_school_enrollment ON public.exam_results USING btree (school_id, enrollment_id);
CREATE INDEX idx_exam_subjects_exam ON public.exam_subjects USING btree (exam_id);
CREATE INDEX idx_exams_school_year ON public.exams USING btree (school_id, academic_year_id, status);
CREATE INDEX idx_fk_044b67c4e85bc265 ON public.ai_execution_runs USING btree (conversation_id);
CREATE INDEX idx_fk_0bab0b0cc5c97a42 ON public.notifications USING btree (school_id);
CREATE INDEX idx_fk_11728d2d321c86d4 ON public.exam_results USING btree (enrollment_id);
CREATE INDEX idx_fk_1740eca38e0b5988 ON public.attendance_sessions USING btree (created_by);
CREATE INDEX idx_fk_1aceb06e21647cc6 ON public.attendance_sessions USING btree (academic_year_id);
CREATE INDEX idx_fk_2ac4f07ba11c1652 ON public.lessons USING btree (section_id);
CREATE INDEX idx_fk_2c222de6d64e743a ON public.fee_payments USING btree (received_by);
CREATE INDEX idx_fk_3171d3d0a9e8007e ON public.leave_requests USING btree (leave_type_id);
CREATE INDEX idx_fk_346665887e7b24c9 ON public.exams USING btree (created_by);
CREATE INDEX idx_fk_35544fcec22f71ff ON public.fee_invoices USING btree (enrollment_id);
CREATE INDEX idx_fk_40f5586232eab6be ON public.fee_structures USING btree (grade_id);
CREATE INDEX idx_fk_568e7ff64e38af14 ON public.exam_subjects USING btree (school_id);
CREATE INDEX idx_fk_69b5dd23b1a42c49 ON public.timetable_entries USING btree (subject_id);
CREATE INDEX idx_fk_6cc6c43dcc26a7e9 ON public.fee_invoice_items USING btree (school_id);
CREATE INDEX idx_fk_78e073eba40b2641 ON public.timetable_entries USING btree (teacher_user_id);
CREATE INDEX idx_fk_822b68e725f04162 ON public.fee_structures USING btree (created_by);
CREATE INDEX idx_fk_83875e746a918204 ON public.lessons USING btree (curriculum_unit_id);
CREATE INDEX idx_fk_a77b947588018dfa ON public.lessons USING btree (subject_id);
CREATE INDEX idx_fk_b27b777da99296a5 ON public.ai_execution_runs USING btree (organization_id);
CREATE INDEX idx_fk_b5bcf14389998c10 ON public.attendance_records USING btree (marked_by);
CREATE INDEX idx_fk_ba0bf4a9ac355c65 ON public.exams USING btree (academic_year_id);
CREATE INDEX idx_fk_be521616d6cde2d2 ON public.fee_invoice_items USING btree (fee_structure_id);
CREATE INDEX idx_fk_c486d5c11d2bc15d ON public.attendance_records USING btree (school_id);
CREATE INDEX idx_fk_c762a5984d7fc594 ON public.exam_subjects USING btree (subject_id);
CREATE INDEX idx_fk_c8f990254ce3c14a ON public.communication_campaigns USING btree (created_by);
CREATE INDEX idx_fk_d657cb3b3629bfc4 ON public.lessons USING btree (created_by);
CREATE INDEX idx_fk_d6dcb64b846755b3 ON public.exam_results USING btree (entered_by);
CREATE INDEX idx_fk_db5809a7d5255589 ON public.student_fee_assignments USING btree (fee_structure_id);
CREATE INDEX idx_fk_dc19650ab5ad97be ON public.attendance_records USING btree (enrollment_id);
CREATE INDEX idx_fk_dfecc79061350a3c ON public.notification_preferences USING btree (school_id);
CREATE INDEX idx_fk_e46d42b1aac7de72 ON public.fee_structures USING btree (academic_year_id);
CREATE INDEX idx_fk_ea4dc4cfef9b2c30 ON public.student_fee_assignments USING btree (assigned_by);
CREATE INDEX idx_fk_efc9f38ca9cf9f92 ON public.fee_invoices USING btree (created_by);
CREATE INDEX idx_fk_f898632dc573559a ON public.curriculum_units USING btree (subject_id);
CREATE INDEX idx_guardians_school ON public.guardians USING btree (school_id);
CREATE INDEX idx_guardians_school_name ON public.guardians USING btree (school_id, full_name);
CREATE INDEX idx_guardians_user ON public.guardians USING btree (user_id);
CREATE INDEX idx_lessons_school_section_date ON public.lessons USING btree (school_id, section_id, scheduled_date);
CREATE INDEX idx_org_members_org_user ON public.organization_memberships USING btree (organization_id, user_id);
CREATE INDEX idx_org_members_user ON public.organization_memberships USING btree (user_id);
CREATE INDEX idx_school_members_school_user ON public.school_memberships USING btree (school_id, user_id);
CREATE INDEX idx_school_members_user ON public.school_memberships USING btree (user_id);
CREATE INDEX idx_schools_org ON public.schools USING btree (organization_id);
CREATE INDEX idx_sections_grade ON public.sections USING btree (grade_id);
CREATE INDEX idx_student_guardians_guardian ON public.student_guardians USING btree (guardian_id);
CREATE INDEX idx_student_guardians_student ON public.student_guardians USING btree (student_id);
CREATE INDEX idx_students_school ON public.students USING btree (school_id);
CREATE INDEX idx_students_school_name ON public.students USING btree (school_id, first_name, last_name);
CREATE INDEX idx_students_school_status ON public.students USING btree (school_id, status);
CREATE INDEX idx_timetable_school_section_day ON public.timetable_entries USING btree (school_id, section_id, day_of_week);
CREATE INDEX import_batches_academic_year_idx ON public.import_batches USING btree (academic_year_id);
CREATE INDEX import_batches_created_by_idx ON public.import_batches USING btree (created_by);
CREATE INDEX import_batches_school_created_idx ON public.import_batches USING btree (school_id, created_at DESC);
CREATE INDEX import_batches_school_idx ON public.import_batches USING btree (school_id);
CREATE INDEX import_rows_batch_status_idx ON public.import_rows USING btree (batch_id, status, row_number);
CREATE INDEX leave_requests_school_dates_idx ON public.leave_requests USING btree (school_id, start_date, end_date);
CREATE INDEX leave_requests_staff_idx ON public.leave_requests USING btree (staff_id, status);
CREATE INDEX notifications_unread_idx ON public.notifications USING btree (user_id, school_id, created_at DESC) WHERE (read_at IS NULL);
CREATE INDEX notifications_user_school_created_idx ON public.notifications USING btree (user_id, school_id, created_at DESC);
CREATE INDEX role_permissions_permission_idx ON public.role_permissions USING btree (permission_id);
CREATE INDEX school_database_provisioning_organization_id_idx ON public.school_database_provisioning USING btree (organization_id);
CREATE INDEX staff_school_status_idx ON public.staff_members USING btree (school_id, status);
CREATE INDEX student_fee_assignments_school_enrollment_idx ON public.student_fee_assignments USING btree (school_id, enrollment_id);
CREATE INDEX user_roles_org_idx ON public.user_roles USING btree (organization_id) WHERE (organization_id IS NOT NULL);
CREATE INDEX user_roles_role_idx ON public.user_roles USING btree (role_id);
CREATE INDEX user_roles_school_idx ON public.user_roles USING btree (school_id) WHERE (school_id IS NOT NULL);
CREATE INDEX user_roles_user_idx ON public.user_roles USING btree (user_id);
