import { NextResponse } from "next/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { optionalString, optionalUuid, stringValue, uuidValue, type GatewayRequest } from "@/lib/gateway/types";
function safeError(error: unknown){const m=error instanceof Error?error.message:"Gateway request failed";if(/required|must be|valid UUID|text/i.test(m))return m;if(/already exists|duplicate key/i.test(m))return "This record already exists for this school";if(/not found|does not belong|not active|permission|access denied|unauthorized|forbidden/i.test(m))return "The requested operation is not permitted";return "Unable to complete the request. Please try again.";}
export async function POST(request:Request){try{const body=(await request.json()) as GatewayRequest;const payload=body.payload??{};if(!body.action||typeof body.action!=="string")return NextResponse.json({error:"action is required"},{status:400});const supabase=await createSupabaseServerClient();const {data:claimsData,error:claimsError}=await supabase.auth.getClaims();const userId=claimsData?.claims?.sub?String(claimsData.claims.sub):null;if(claimsError||!userId)return NextResponse.json({error:"Authentication required"},{status:401});
if(body.action==="workspace.context"){const [{data:organizations},{data:schools},{data:roles}]=await Promise.all([supabase.from("organization_memberships").select("organization_id,role,status,organizations(id,name,slug,status)").eq("user_id",userId),supabase.from("school_memberships").select("school_id,role,status,schools(id,organization_id,name,code,status)").eq("user_id",userId),supabase.from("user_roles").select("id,organization_id,school_id,roles(key,name,scope)").eq("user_id",userId)]);return NextResponse.json({organizations:organizations??[],schools:schools??[],roles:roles??[]});}
if(body.action==="school.sections"){const {data,error}=await supabase.from("sections").select("id,name,capacity").eq("school_id",uuidValue(payload,"schoolId")).eq("grade_id",uuidValue(payload,"gradeId")).order("name");if(error)throw new Error(error.message);return NextResponse.json({data:data??[]});}
if(body.action==="student.search"){const schoolId=uuidValue(payload,"schoolId"),query=optionalString(payload,"query"),status=optionalString(payload,"status");const lim=Math.min(Math.max(Math.trunc(Number(payload.limit??50)),1),100);let q=supabase.from("students").select("id,school_id,admission_number,first_name,middle_name,last_name,date_of_birth,gender,email,phone,status,created_at,updated_at").eq("school_id",schoolId).order("first_name").order("last_name").limit(Number.isFinite(lim)?lim:50);if(status)q=q.eq("status",status);if(query){const s=query.replace(/[%_,]/g," ").trim();if(s)q=q.or(`admission_number.ilike.%${s}%,first_name.ilike.%${s}%,middle_name.ilike.%${s}%,last_name.ilike.%${s}%`)}const {data,error}=await q;if(error)throw new Error(error.message);return NextResponse.json({data:data??[]});}
if(body.action==="student.get"){const schoolId=uuidValue(payload,"schoolId"),studentId=uuidValue(payload,"studentId");const [{data:student,error:se},{data:guardians,error:ge},{data:enrollments,error:ee}]=await Promise.all([supabase.from("students").select("id,school_id,admission_number,first_name,middle_name,last_name,date_of_birth,gender,email,phone,status,metadata,created_at,updated_at").eq("id",studentId).eq("school_id",schoolId).maybeSingle(),supabase.from("student_guardians").select("is_primary,guardians(id,full_name,relationship,phone,email,address,user_id)").eq("student_id",studentId),supabase.from("student_enrollments").select("id,academic_year_id,grade_id,section_id,roll_number,status,created_at,academic_years(name,start_date,end_date,is_current),grades(name,code),sections(name,capacity)").eq("student_id",studentId).eq("school_id",schoolId).order("created_at",{ascending:false})]);if(se)throw new Error(se.message);if(ge)throw new Error(ge.message);if(ee)throw new Error(ee.message);if(!student)return NextResponse.json({error:"Student not found"},{status:404});return NextResponse.json({data:{student,guardians:guardians??[],enrollments:enrollments??[]}});}
const admin=createSupabaseAdminClient();
if(body.action==="school.role.assign"){
  const schoolId=uuidValue(payload,"schoolId");
  const email=stringValue(payload,"email").trim().toLowerCase();
  const roleKey=stringValue(payload,"role");
  if(!["admin","teacher","staff"].includes(roleKey)) throw new Error("Invalid school role");
  let targetUserId:string|null=null;
  const usersResult=await admin.auth.admin.listUsers({page:1,perPage:1000});
  if(usersResult.error) throw new Error(usersResult.error.message);
  const existing=usersResult.data.users.find((u)=>u.email?.toLowerCase()===email);
  if(existing) targetUserId=existing.id;
  else {
    const invited=await admin.auth.admin.inviteUserByEmail(email,{data:{school_role:roleKey}});
    if(invited.error) throw new Error(invited.error.message);
    targetUserId=invited.data.user?.id ?? null;
  }
  if(!targetUserId) throw new Error("Unable to create or find the user");
  const {data,error}=await admin.rpc("assign_school_role",{p_actor_user_id:userId,p_school_id:schoolId,p_target_user_id:targetUserId,p_role_key:roleKey});
  if(error) throw new Error(error.message);
  return NextResponse.json({data,invited:!existing});
}
const rpcMap:any={"subject.create":["create_subject",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_name:stringValue(payload,"name"),p_code:stringValue(payload,"code"),p_description:optionalString(payload,"description")}],"curriculum.unit.create":["create_curriculum_unit",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_grade_id:uuidValue(payload,"gradeId"),p_subject_id:uuidValue(payload,"subjectId"),p_name:stringValue(payload,"name"),p_sequence_no:Number(payload.sequenceNo??1),p_description:optionalString(payload,"description")}],"lesson.create":["create_lesson",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_section_id:uuidValue(payload,"sectionId"),p_subject_id:uuidValue(payload,"subjectId"),p_curriculum_unit_id:optionalUuid(payload,"curriculumUnitId"),p_title:stringValue(payload,"title"),p_content:optionalString(payload,"content"),p_scheduled_date:optionalString(payload,"scheduledDate")}],"timetable.entry.create":["create_timetable_entry",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_section_id:uuidValue(payload,"sectionId"),p_subject_id:uuidValue(payload,"subjectId"),p_teacher_user_id:optionalUuid(payload,"teacherUserId"),p_day_of_week:Number(payload.dayOfWeek),p_period_no:Number(payload.periodNo),p_starts_at:optionalString(payload,"startsAt"),p_ends_at:optionalString(payload,"endsAt"),p_room:optionalString(payload,"room")}],"exam.create":["create_exam",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_academic_year_id:uuidValue(payload,"academicYearId"),p_name:stringValue(payload,"name"),p_exam_type:stringValue(payload,"examType"),p_start_date:optionalString(payload,"startDate"),p_end_date:optionalString(payload,"endDate"),p_max_marks:Number(payload.maxMarks??100)}],"exam.subject.create":["create_exam_subject",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_exam_id:uuidValue(payload,"examId"),p_subject_id:uuidValue(payload,"subjectId"),p_exam_date:optionalString(payload,"examDate"),p_max_marks:Number(payload.maxMarks??100),p_pass_marks:Number(payload.passMarks??35)}]};
if(rpcMap[body.action]){const [fn,args]=rpcMap[body.action];const {data,error}=await admin.rpc(fn,args);if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="communication.create"){const targetIds=Array.isArray(payload.targetStudentIds)?payload.targetStudentIds.filter((v):v is string=>typeof v==="string"):null;const {data,error}=await admin.rpc("create_communication_campaign",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_title:stringValue(payload,"title"),p_body:stringValue(payload,"body"),p_channel:stringValue(payload,"channel"),p_audience_type:stringValue(payload,"audienceType"),p_target_student_ids:targetIds,p_scheduled_at:optionalString(payload,"scheduledAt")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="communication.send"){const {data,error}=await admin.rpc("send_communication_campaign",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_campaign_id:uuidValue(payload,"campaignId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="communication.list"){const {data,error}=await admin.rpc("get_communication_campaigns",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId")});if(error)throw new Error(error.message);return NextResponse.json({data:data??[]});}
if(body.action==="notification.list"){const {data,error}=await admin.rpc("get_notifications",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_limit:Math.min(Math.max(Number(payload.limit??50),1),100)});if(error)throw new Error(error.message);return NextResponse.json({data:data??[]});}
if(body.action==="notification.read"){const {data,error}=await admin.rpc("mark_notification_read",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_notification_id:uuidValue(payload,"notificationId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="notification.read_all"){const {data,error}=await admin.rpc("mark_all_notifications_read",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="notification.preferences.get"){const {data,error}=await admin.rpc("get_notification_preferences",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="data.import.commit"){const {data,error}=await admin.rpc("commit_import_batch",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_batch_id:uuidValue(payload,"batchId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="parent.dashboard"){const {data,error}=await admin.rpc("get_parent_dashboard",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="notification.preferences.set"){const {data,error}=await admin.rpc("set_notification_preferences",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_in_app_enabled:Boolean(payload.in_app_enabled),p_email_enabled:Boolean(payload.email_enabled),p_sms_enabled:Boolean(payload.sms_enabled),p_whatsapp_enabled:Boolean(payload.whatsapp_enabled)});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="exam.results.save"){if(!Array.isArray(payload.results))throw new Error("results must be an array");const {data,error}=await admin.rpc("save_exam_results",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_exam_subject_id:uuidValue(payload,"examSubjectId"),p_results:payload.results});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="exam.results.get"){const {data,error}=await admin.rpc("get_exam_results",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_exam_subject_id:uuidValue(payload,"examSubjectId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="finance.structure.create"){const {data,error}=await admin.rpc("create_fee_structure",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_academic_year_id:uuidValue(payload,"academicYearId"),p_name:stringValue(payload,"name"),p_fee_type:stringValue(payload,"feeType"),p_frequency:stringValue(payload,"frequency"),p_amount:Number(payload.amount),p_due_day:payload.dueDay===null||payload.dueDay===undefined||payload.dueDay===""?null:Number(payload.dueDay),p_grade_id:optionalUuid(payload,"gradeId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="finance.assignment.create"){const {data,error}=await admin.rpc("assign_student_fee",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_enrollment_id:uuidValue(payload,"enrollmentId"),p_fee_structure_id:uuidValue(payload,"feeStructureId"),p_amount:payload.amount===null||payload.amount===undefined||payload.amount===""?null:Number(payload.amount),p_discount:Number(payload.discount??0)});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="finance.invoice.create"){if(!Array.isArray(payload.items))throw new Error("items must be an array");const {data,error}=await admin.rpc("create_fee_invoice",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_enrollment_id:uuidValue(payload,"enrollmentId"),p_invoice_number:stringValue(payload,"invoiceNumber"),p_due_date:stringValue(payload,"dueDate"),p_items:payload.items,p_discount:Number(payload.discount??0),p_notes:optionalString(payload,"notes")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="finance.payment.record"){const {data,error}=await admin.rpc("record_fee_payment",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_invoice_id:uuidValue(payload,"invoiceId"),p_receipt_number:stringValue(payload,"receiptNumber"),p_amount:Number(payload.amount),p_payment_method:stringValue(payload,"paymentMethod"),p_reference:optionalString(payload,"reference")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="finance.balance.get"){const {data,error}=await admin.rpc("get_student_fee_balance",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_enrollment_id:uuidValue(payload,"enrollmentId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="attendance.roster"){const {data,error}=await admin.rpc("get_attendance_roster",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_section_id:uuidValue(payload,"sectionId"),p_academic_year_id:uuidValue(payload,"academicYearId"),p_attendance_date:stringValue(payload,"attendanceDate")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="attendance.save"){if(!Array.isArray(payload.records))throw new Error("records must be an array");const {data,error}=await admin.rpc("save_attendance",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_academic_year_id:uuidValue(payload,"academicYearId"),p_section_id:uuidValue(payload,"sectionId"),p_attendance_date:stringValue(payload,"attendanceDate"),p_records:payload.records,p_status:optionalString(payload,"status")??"submitted",p_notes:optionalString(payload,"notes")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="attendance.student.summary"){const {data,error}=await admin.rpc("get_student_attendance_summary",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_student_id:uuidValue(payload,"studentId"),p_academic_year_id:uuidValue(payload,"academicYearId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="school.onboarding.save"){const {data,error}=await admin.rpc("save_school_onboarding",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_status:optionalString(payload,"status")??"in_progress",p_current_step:Number(payload.currentStep??1),p_answers:payload.answers&&typeof payload.answers==="object"?payload.answers:{}});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="workspace.bootstrap"){const {data,error}=await admin.rpc("bootstrap_school_workspace",{p_actor_user_id:userId,p_org_name:stringValue(payload,"organizationName"),p_school_name:stringValue(payload,"schoolName"),p_school_code:stringValue(payload,"schoolCode")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="academic_year.create"){const {data,error}=await admin.rpc("create_academic_year",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_name:stringValue(payload,"name"),p_start_date:stringValue(payload,"startDate"),p_end_date:stringValue(payload,"endDate"),p_is_current:Boolean(payload.isCurrent)});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="grade.create"){const {data,error}=await admin.rpc("create_grade",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_name:stringValue(payload,"name"),p_code:stringValue(payload,"code"),p_sort_order:Number(payload.sortOrder??0)});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="section.create"){const raw=payload.capacity===""||payload.capacity===undefined?null:Number(payload.capacity);const {data,error}=await admin.rpc("create_section",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_grade_id:uuidValue(payload,"gradeId"),p_name:stringValue(payload,"name"),p_capacity:raw===null||Number.isFinite(raw)?raw:null});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="student.create"){const {data,error}=await admin.rpc("create_student",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_admission_number:stringValue(payload,"admissionNumber"),p_first_name:stringValue(payload,"firstName"),p_middle_name:optionalString(payload,"middleName"),p_last_name:optionalString(payload,"lastName"),p_date_of_birth:optionalString(payload,"dateOfBirth"),p_gender:optionalString(payload,"gender"),p_email:optionalString(payload,"email"),p_phone:optionalString(payload,"phone"),p_status:optionalString(payload,"status")??"active"});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="student.update"){const {data,error}=await admin.rpc("update_student",{p_actor_user_id:userId,p_student_id:uuidValue(payload,"studentId"),p_school_id:uuidValue(payload,"schoolId"),p_admission_number:stringValue(payload,"admissionNumber"),p_first_name:stringValue(payload,"firstName"),p_middle_name:optionalString(payload,"middleName"),p_last_name:optionalString(payload,"lastName"),p_date_of_birth:optionalString(payload,"dateOfBirth"),p_gender:optionalString(payload,"gender"),p_email:optionalString(payload,"email"),p_phone:optionalString(payload,"phone"),p_status:optionalString(payload,"status")??"active"});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="guardian.create"){const address=payload.address&&typeof payload.address==="object"?payload.address:{};const {data,error}=await admin.rpc("create_guardian",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_full_name:stringValue(payload,"fullName"),p_relationship:optionalString(payload,"relationship"),p_phone:optionalString(payload,"phone"),p_email:optionalString(payload,"email"),p_address:address,p_user_id:optionalUuid(payload,"userId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="student.guardian.link"){const {data,error}=await admin.rpc("link_student_guardian",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_student_id:uuidValue(payload,"studentId"),p_guardian_id:uuidValue(payload,"guardianId"),p_is_primary:Boolean(payload.isPrimary)});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="enrollment.create"){const {data,error}=await admin.rpc("create_student_enrollment",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_student_id:uuidValue(payload,"studentId"),p_academic_year_id:uuidValue(payload,"academicYearId"),p_grade_id:uuidValue(payload,"gradeId"),p_section_id:optionalUuid(payload,"sectionId"),p_roll_number:optionalString(payload,"rollNumber"),p_status:optionalString(payload,"status")??"active"});if(error)throw new Error(error.message);return NextResponse.json({data});}
return NextResponse.json({error:"Unsupported gateway action"},{status:400});}catch(error){console.error("Gateway request failed",error);return NextResponse.json({error:safeError(error)},{status:400});}}
