import { NextResponse } from "next/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { optionalString, optionalUuid, stringValue, uuidValue, type GatewayRequest } from "@/lib/gateway/types";
function safeError(error: unknown){const m=error instanceof Error?error.message:"Gateway request failed";if(/required|must be|valid UUID|text|range|before/i.test(m))return m;if(/already exists|duplicate key/i.test(m))return "This record already exists for this school";if(/not found|does not belong|not active|permission|access denied|unauthorized|forbidden/i.test(m))return "The requested operation is not permitted";return "Unable to complete the request. Please try again.";}
export async function POST(request:Request){try{const body=(await request.json()) as GatewayRequest;const payload=body.payload??{};const supabase=await createSupabaseServerClient();const {data:claimsData,error:claimsError}=await supabase.auth.getClaims();const userId=claimsData?.claims?.sub?String(claimsData.claims.sub):null;if(claimsError||!userId)return NextResponse.json({error:"Authentication required"},{status:401});
if(body.action==="workspace.context"){const [{data:organizations},{data:schools},{data:roles}]=await Promise.all([supabase.from("organization_memberships").select("organization_id,role,status,organizations(id,name,slug,status)").eq("user_id",userId),supabase.from("school_memberships").select("school_id,role,status,schools(id,organization_id,name,code,status)").eq("user_id",userId),supabase.from("user_roles").select("id,organization_id,school_id,roles(key,name,scope)").eq("user_id",userId)]);return NextResponse.json({organizations:organizations??[],schools:schools??[],roles:roles??[]});}
if(body.action==="school.sections"){const {data,error}=await supabase.from("sections").select("id,name,capacity").eq("school_id",uuidValue(payload,"schoolId")).eq("grade_id",uuidValue(payload,"gradeId")).order("name");if(error)throw new Error(error.message);return NextResponse.json({data:data??[]});}
if(body.action==="student.search"){const schoolId=uuidValue(payload,"schoolId"),query=optionalString(payload,"query"),status=optionalString(payload,"status");const lim=Math.min(Math.max(Math.trunc(Number(payload.limit??50)),1),100);let q=supabase.from("students").select("id,school_id,admission_number,first_name,middle_name,last_name,date_of_birth,gender,email,phone,status,created_at,updated_at").eq("school_id",schoolId).order("first_name").order("last_name").limit(Number.isFinite(lim)?lim:50);if(status)q=q.eq("status",status);if(query){const s=query.replace(/[%_,]/g," ").trim();if(s)q=q.or(`admission_number.ilike.%${s}%,first_name.ilike.%${s}%,middle_name.ilike.%${s}%,last_name.ilike.%${s}%`)}const {data,error}=await q;if(error)throw new Error(error.message);return NextResponse.json({data:data??[]});}
const admin=createSupabaseAdminClient();
const rpcMap:any={"subject.create":["create_subject",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_name:stringValue(payload,"name"),p_code:stringValue(payload,"code"),p_description:optionalString(payload,"description")}],"curriculum.unit.create":["create_curriculum_unit",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_grade_id:uuidValue(payload,"gradeId"),p_subject_id:uuidValue(payload,"subjectId"),p_name:stringValue(payload,"name"),p_sequence_no:Number(payload.sequenceNo??1),p_description:optionalString(payload,"description")}],"lesson.create":["create_lesson",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_section_id:uuidValue(payload,"sectionId"),p_subject_id:uuidValue(payload,"subjectId"),p_curriculum_unit_id:optionalUuid(payload,"curriculumUnitId"),p_title:stringValue(payload,"title"),p_content:optionalString(payload,"content"),p_scheduled_date:optionalString(payload,"scheduledDate")}],"timetable.entry.create":["create_timetable_entry",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_section_id:uuidValue(payload,"sectionId"),p_subject_id:uuidValue(payload,"subjectId"),p_teacher_user_id:optionalUuid(payload,"teacherUserId"),p_day_of_week:Number(payload.dayOfWeek),p_period_no:Number(payload.periodNo),p_starts_at:optionalString(payload,"startsAt"),p_ends_at:optionalString(payload,"endsAt" )}],"exam.create":["create_exam",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_academic_year_id:uuidValue(payload,"academicYearId"),p_name:stringValue(payload,"name"),p_exam_type:stringValue(payload,"examType"),p_start_date:optionalString(payload,"startDate"),p_end_date:optionalString(payload,"endDate"),p_max_marks:Number(payload.maxMarks??100)}],"exam.subject.create":["create_exam_subject",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_exam_id:uuidValue(payload,"examId"),p_subject_id:uuidValue(payload,"subjectId"),p_exam_date:optionalString(payload,"examDate"),p_max_marks:Number(payload.maxMarks??100),p_pass_marks:Number(payload.passMarks??35)}]};
if(rpcMap[body.action]){const [fn,args]=rpcMap[body.action];const {data,error}=await admin.rpc(fn,args);if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="exam.results.save"){if(!Array.isArray(payload.results))throw new Error("results must be an array");const {data,error}=await admin.rpc("save_exam_results",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_exam_subject_id:uuidValue(payload,"examSubjectId"),p_results:payload.results});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="exam.results.get"){const {data,error}=await admin.rpc("get_exam_results",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_exam_subject_id:uuidValue(payload,"examSubjectId")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="attendance.roster"){const {data,error}=await admin.rpc("get_attendance_roster",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_section_id:uuidValue(payload,"sectionId"),p_academic_year_id:uuidValue(payload,"academicYearId"),p_attendance_date:stringValue(payload,"attendanceDate")});if(error)throw new Error(error.message);return NextResponse.json({data});}
if(body.action==="attendance.save"){if(!Array.isArray(payload.records))throw new Error("records must be an array");const {data,error}=await admin.rpc("save_attendance",{p_actor_user_id:userId,p_school_id:uuidValue(payload,"schoolId"),p_academic_year_id:uuidValue(payload,"academicYearId"),p_section_id:uuidValue(payload,"sectionId"),p_attendance_date:stringValue(payload,"attendanceDate"),p_records:payload.records,p_status:optionalString(payload,"status")??"submitted",p_notes:optionalString(payload,"notes")});if(error)throw new Error(error.message);return NextResponse.json({data});}
return NextResponse.json({error:"Unsupported gateway action"},{status:400});}catch(error){console.error("Gateway request failed",error);return NextResponse.json({error:safeError(error)},{status:400});}}
