"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
type Subject={id:string;name:string;code:string;description:string|null;is_active:boolean}; type Grade={id:string;name:string;code:string}; type Section={id:string;name:string;gradeId:string;gradeName:string}; type Unit={id:string;name:string;gradeId:string;subjectId:string;sequenceNo:number;description:string|null;gradeName:string;subjectName:string}; type Lesson={id:string;title:string;sectionId:string;subjectId:string;scheduledDate:string|null;status:string;content:string|null;sectionName:string;subjectName:string}; type TT={id:string;sectionId:string;subjectId:string;teacherUserId:string|null;day:number;period:number;startsAt:string|null;endsAt:string|null;room:string|null;sectionName:string;subjectName:string};
export default function AcademicBoard({schoolId,school,grades,sections,subjects,units,lessons,timetable}:{schoolId:string;school:{name:string;code:string};grades:Grade[];sections:Section[];subjects:Subject[];units:Unit[];lessons:Lesson[];timetable:TT[]}){
 const [tab,setTab]=useState("subjects"); const [name,setName]=useState(""); const [code,setCode]=useState(""); const [description,setDescription]=useState(""); const [gradeId,setGradeId]=useState(grades[0]?.id??""); const [subjectId,setSubjectId]=useState(subjects[0]?.id??""); const [sectionId,setSectionId]=useState(sections[0]?.id??""); const [title,setTitle]=useState(""); const [date,setDate]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 const filteredUnits=useMemo(()=>units.filter(u=>u.gradeId===gradeId),[units,gradeId]);
 async function call(action:string,payload:any){setError("");setMessage("");const r=await fetch("/api/gateway",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,payload:{schoolId,...payload}})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Request failed");return b.data;}
 async function createSubject(){try{await call("subject.create",{name,code,description});setMessage("Subject created. Refresh to see it.");setName("");setCode("");setDescription("");}catch(e){setError(e instanceof Error?e.message:"Unable to create subject")}}
 async function createUnit(){try{await call("curriculum.unit.create",{gradeId,subjectId,name,sequenceNo:1,description});setMessage("Curriculum unit created. Refresh to see it.");setName("");}catch(e){setError(e instanceof Error?e.message:"Unable to create unit")}}
 async function createLesson(){try{await call("lesson.create",{sectionId,subjectId,curriculumUnitId:null,title,content:description,scheduledDate:date||null});setMessage("Lesson created. Refresh to see it.");setTitle("");}catch(e){setError(e instanceof Error?e.message:"Unable to create lesson")}}
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">E</span><span>EduFlow AI</span></div><p className="sidebar-label">Workspace</p><nav className="side-nav"><Link href="/">Overview</Link><Link href={`/students?schoolId=${schoolId}`}>Students</Link><Link href={`/attendance?schoolId=${schoolId}`}>Attendance</Link><Link className="active" href={`/academic?schoolId=${schoolId}`}>Academic</Link><Link href="/school/setup">School setup</Link></nav><div className="sidebar-footer"><strong>{school.name}</strong><span>{school.code}</span></div></aside><section className="dashboard"><header className="topbar"><div><p className="eyebrow">V5 · Academic</p><h1>Academic management</h1></div></header><section className="workspace-banner"><div><span className="muted">Curriculum workspace</span><h2>Subjects, curriculum, lessons & timetable</h2><p>School-scoped academic planning with RBAC and audit logging.</p></div><div className="workspace-badge">RBAC + audit</div></section><nav className="student-toolbar">{["subjects","curriculum","lessons","timetable"].map(t=><button key={t} className={tab===t?"attendance-status active":"attendance-status"} onClick={()=>setTab(t)}>{t}</button>)}</nav>{error&&<p className="error page-message">{error}</p>}{message&&<p className="success page-message">{message}</p>}
 {tab==="subjects"&&<><section className="student-table-card"><h3>Add subject</h3><div className="student-toolbar"><input placeholder="Subject name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Code" value={code} onChange={e=>setCode(e.target.value)}/><input placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><button className="primary-link" onClick={createSubject} disabled={!name||!code}>Create</button></div></section><section className="student-table-card"><h3>Subjects ({subjects.length})</h3><table className="student-table"><tbody>{subjects.map(s=><tr key={s.id}><td><strong>{s.name}</strong></td><td>{s.code}</td><td>{s.description||"—"}</td><td>{s.is_active?"Active":"Inactive"}</td></tr>)}</tbody></table></section></>}
 {tab==="curriculum"&&<><section className="student-table-card"><h3>Add curriculum unit</h3><div className="student-toolbar"><select value={gradeId} onChange={e=>setGradeId(e.target.value)}>{grades.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select value={subjectId} onChange={e=>setSubjectId(e.target.value)}>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input placeholder="Unit name" value={name} onChange={e=>setName(e.target.value)}/><button className="primary-link" onClick={createUnit} disabled={!name||!gradeId||!subjectId}>Create</button></div></section><section className="student-table-card"><h3>Curriculum units</h3><table className="student-table"><tbody>{filteredUnits.map(u=><tr key={u.id}><td>{u.gradeName}</td><td>{u.subjectName}</td><td><strong>{u.name}</strong></td><td>Unit {u.sequenceNo}</td></tr>)}</tbody></table></section></>}
 {tab==="lessons"&&<><section className="student-table-card"><h3>Create lesson</h3><div className="student-toolbar"><select value={sectionId} onChange={e=>setSectionId(e.target.value)}>{sections.map(s=><option key={s.id} value={s.id}>{s.gradeName} · {s.name}</option>)}</select><select value={subjectId} onChange={e=>setSubjectId(e.target.value)}>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input placeholder="Lesson title" value={title} onChange={e=>setTitle(e.target.value)}/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="primary-link" onClick={createLesson} disabled={!title}>Create</button></div></section><section className="student-table-card"><h3>Recent lessons</h3><table className="student-table"><tbody>{lessons.map(l=><tr key={l.id}><td>{l.scheduledDate||"—"}</td><td>{l.sectionName}</td><td>{l.subjectName}</td><td><strong>{l.title}</strong></td><td>{l.status}</td></tr>)}</tbody></table></section></>}
 {tab==="timetable"&&<section className="student-table-card"><h3>Timetable</h3><table className="student-table"><thead><tr><th>Day</th><th>Period</th><th>Section</th><th>Subject</th><th>Time</th><th>Room</th></tr></thead><tbody>{timetable.map(t=><tr key={t.id}><td>{["","Mon","Tue","Wed","Thu","Fri","Sat","Sun"][t.day]}</td><td>{t.period}</td><td>{t.sectionName}</td><td>{t.subjectName}</td><td>{t.startsAt||"—"}–{t.endsAt||"—"}</td><td>{t.room||"—"}</td></tr>)}</tbody></table>{timetable.length===0&&<p className="empty">No timetable entries yet. Entries can be added through the secured gateway.</p>}</section>}
 </section></main>;
}
