"use client";
import Link from "next/link";
import {useState} from "react";

type Tool={name?:string;slug?:string;risk_level?:string;handler_key?:string};
type Plan={run_id?:string;status?:string;intent?:string;tool?:Tool;authorization?:{allowed?:boolean;reason?:string};input?:{request?:string};reused?:boolean};
type ResponseData={ok?:boolean;plan?:Plan;result?:unknown;error?:string};

export default function AiBoard({schoolId,school}:{schoolId:string;school:{name:string;code:string}}){
 const [message,setMessage]=useState(""),[loading,setLoading]=useState(false),[data,setData]=useState<ResponseData|null>(null),[error,setError]=useState("");
 const ask=async()=>{if(!message.trim())return;setLoading(true);setError("");setData(null);try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({schoolId,message:message.trim(),idempotencyKey:crypto.randomUUID()})});const b=await r.json();if(!r.ok)throw new Error(b.error||"AI request failed");setData(b)}catch(e){setError(e instanceof Error?e.message:"AI request failed")}finally{setLoading(false)}};
 const plan=data?.plan,tool=plan?.tool;
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">E</span><span>EduFlow AI</span></div><p className="sidebar-label">AI</p><nav className="side-nav"><Link href="/">Overview</Link><Link className="active" href={"/ai?schoolId="+schoolId}>AI Assistant</Link><Link href={"/students?schoolId="+schoolId}>Students</Link><Link href={"/analytics?schoolId="+schoolId}>Analytics</Link><Link href={"/attendance?schoolId="+schoolId}>Attendance</Link></nav><div className="sidebar-footer"><strong>{school.name}</strong><span>{school.code}</span></div></aside><section className="dashboard"><header className="topbar"><div><p className="eyebrow">V15 · AI Orchestration</p><h1>School AI Assistant</h1></div></header><section className="workspace-banner"><div><span className="muted">Controlled execution</span><h2>Understand → authorize → execute → audit</h2><p>Every AI request is scoped to this school, checked against permissions, recorded in the execution ledger, and audited.</p></div><div className="workspace-badge">Tool Registry</div></section><section className="workspace-banner"><div style={{width:"100%"}}><textarea aria-label="AI request" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Try: Show the management dashboard, find student 1001, or show attendance for admission number 1001" rows={5} style={{width:"100%",padding:"14px",borderRadius:"12px",border:"1px solid #ddd"}}/><button className="primary-link" disabled={!message.trim()||loading} onClick={()=>void ask()}>{loading?"Working…":"Ask EduFlow AI"}</button></div></section>{error&&<p className="error page-message">{error}</p>}{plan&&<section className="workspace-banner"><div style={{width:"100%"}}><span className="muted">Execution plan</span><h2>{tool?.name||"AI tool"}</h2><p>Intent: {plan.intent||"—"} · Status: {plan.status||"—"} · {plan.reused?"Reused execution":"New execution"}</p><p>Authorization: {plan.authorization?.allowed?"Allowed":"Denied"}{plan.authorization?.reason?" · "+plan.authorization.reason:""}</p>{data?.result!==undefined&&<pre style={{whiteSpace:"pre-wrap",marginTop:"16px",overflowX:"auto"}}>{JSON.stringify(data.result,null,2)}</pre>}{data?.error&&<p className="error">{data.error}</p>}</div></section>}</section></main>;
}