"use client";
import Link from "next/link";
import { useState } from "react";

type Result={total_rows:number;valid_rows:number;invalid_rows:number};
type Preview={batchId:string;sourceSchoolName:string;worksheet:string;rowsParsed:number;validation:Result;safeMode:boolean;writesPerformed:boolean};

export default function ImportBoard({schoolId,school,years,initialYearId}:{schoolId:string;school:{name:string;code:string};years:{id:string;name:string;is_current:boolean}[];initialYearId:string}){
 const [yearId,setYearId]=useState(initialYearId),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const [schoolCsv,setSchoolCsv]=useState<File|null>(null),[schoolPreview,setSchoolPreview]=useState<any>(null),[schoolLoading,setSchoolLoading]=useState(false),[schoolResult,setSchoolResult]=useState<any>(null);
 const previewFile=async()=>{if(!file||!yearId)return;setLoading(true);setError("");setMessage("");try{const form=new FormData();form.append("file",file);form.append("schoolId",schoolId);form.append("academicYearId",yearId);const r=await fetch("/api/import",{method:"POST",body:form});const b=await r.json();if(!r.ok)throw new Error(b.error||"Import preview failed");setPreview(b.data);setMessage("Workbook staged and validated. No student, guardian, or enrollment records were written.");}catch(e){setError(e instanceof Error?e.message:"Import preview failed")}finally{setLoading(false)}};
 const commit=async()=>{if(!preview||preview.validation.invalid_rows>0)return;setLoading(true);setError("");try{const r=await fetch("/api/gateway",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"data.import.commit",payload:{schoolId,batchId:preview.batchId}})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Import commit failed");setMessage("Import committed: "+JSON.stringify(b.data));}catch(e){setError(e instanceof Error?e.message:"Import commit failed")}finally{setLoading(false)}};
 const previewSchool=async()=>{if(!schoolCsv)return;setSchoolLoading(true);setError("");setSchoolResult(null);try{const form=new FormData();form.append("file",schoolCsv);form.append("schoolId",schoolId);const r=await fetch("/api/import/school",{method:"POST",body:form});const b=await r.json();if(r.status===422){setSchoolPreview(b.data);return}if(!r.ok)throw new Error(b.error||"School CSV preview failed");setSchoolPreview(b.data);setMessage("School CSV validated. Nothing has been created yet.");}catch(e){setError(e instanceof Error?e.message:"School CSV preview failed")}finally{setSchoolLoading(false)}};
 const commitSchool=async()=>{if(!schoolCsv||!schoolPreview?.valid)return;setSchoolLoading(true);setError("");try{const form=new FormData();form.append("file",schoolCsv);form.append("schoolId",schoolId);const r=await fetch("/api/import/school",{method:"PUT",body:form});const b=await r.json();if(!r.ok)throw new Error(b.error||"School setup import failed");setSchoolResult(b.data);setMessage("Complete school setup imported successfully.");}catch(e){setError(e instanceof Error?e.message:"School setup import failed")}finally{setSchoolLoading(false)}};
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">E</span><span>EduFlow AI</span></div><p className="sidebar-label">Data</p><nav className="side-nav">
<Link href={`/?schoolId=${schoolId}`}>Overview</Link><Link href={`/analytics?schoolId=${schoolId}`}>Analytics</Link><Link href={`/students?schoolId=${schoolId}`}>Students</Link><Link href={`/academic?schoolId=${schoolId}`}>Academic</Link><Link href={`/attendance?schoolId=${schoolId}`}>Attendance</Link><Link href={`/exams?schoolId=${schoolId}`}>Exams</Link><Link href={`/finance?schoolId=${schoolId}`}>Finance</Link><Link href={`/hr?schoolId=${schoolId}`}>Staff & HR</Link><Link href={`/communication?schoolId=${schoolId}`}>Communication</Link><Link href={`/notifications?schoolId=${schoolId}`}>Notifications</Link><Link href={`/parent?schoolId=${schoolId}`}>Parent Portal</Link><Link className="active" href={`/import?schoolId=${schoolId}`}>Data Import</Link><Link href={`/ai?schoolId=${schoolId}`}>AI Assistant</Link><Link href={`/school/setup?schoolId=${schoolId}`}>School setup</Link></nav><div className="sidebar-footer"><strong>{school.name}</strong><span>{school.code}</span></div></aside>
 <section className="dashboard"><header className="topbar"><div><p className="eyebrow">V14 · Fast School Onboarding</p><h1>Import school data</h1></div></header>
 <section className="workspace-banner"><div><span className="muted">Recommended for new schools</span><h2>One CSV can build the school foundation</h2><p>Upload one simple file and EduFlow AI can create academic years, grades, sections, subjects, students, enrollments, guardians and teacher records in one guided flow.</p></div><div className="workspace-badge">Preview → Validate → Commit</div></section>
 <section className="auth-card"><div><div><span className="muted">Quick School Setup</span><h2>One-CSV onboarding</h2><p>Download the template, fill it in Excel or Google Sheets, export as CSV, then upload it here. Repeated students, classes, subjects and teachers are automatically deduplicated.</p></div><div className="student-toolbar"><a className="secondary-button" href="/school-import-template.csv" download>Download CSV template</a><input aria-label="School setup CSV" type="file" accept=".csv" onChange={e=>{setSchoolCsv(e.target.files?.[0]??null);setSchoolPreview(null);setSchoolResult(null)}}/><button className="primary-link" disabled={!schoolCsv||schoolLoading} onClick={()=>void previewSchool()}>{schoolLoading?"Processing…":"Preview school setup"}</button></div></div></section>
 {schoolPreview&&<section className="workspace-banner"><div><span className="muted">Validation result</span><h2>{schoolPreview.valid?"Ready to import":"Fix these CSV errors first"}</h2>{schoolPreview.valid?<p>{schoolPreview.rowsParsed} rows validated. Preview is non-destructive. The commit will create the school structure and people from this file.</p>:<ul>{(schoolPreview.errors??[]).slice(0,12).map((x:string)=><li key={x}>{x}</li>)}</ul>}</div>{schoolPreview.valid&&<button className="primary-link" disabled={schoolLoading} onClick={()=>void commitSchool()}>Create school data</button>}</section>}
 {schoolResult&&<section className="metric-grid">{Object.entries(schoolResult.created??{}).map(([k,v])=><article className="metric" key={k}><span>{k.replace(/_/g," ")}</span><strong>{String(v)}</strong><small>Created or matched</small></article>)}</section>}
 {schoolResult?.teacher_accounts?.length>0&&<section className="auth-card"><h3>Teacher access</h3><p>Teacher records were created. Accounts marked invited received a Supabase invitation; existing accounts were assigned the Teacher role.</p><ul>{schoolResult.teacher_accounts.map((x:any)=><li key={x.email}>{x.email} — {x.error?"Needs attention":x.invited?"Invitation sent":"Existing account assigned"}</li>)}</ul></section>}
 <section className="workspace-banner"><div><span className="muted">Advanced migration</span><h2>Existing workbook import</h2><p>Keep using the validated workbook flow when you already have a structured student database.</p></div></section>
 <section className="student-toolbar"><select aria-label="Academic year" value={yearId} onChange={e=>setYearId(e.target.value)}>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.is_current?" · Current":""}</option>)}</select><input aria-label="Workbook" type="file" accept=".xlsx,.xlsm" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null)}}/><button className="primary-link" disabled={!file||!yearId||loading} onClick={()=>void previewFile()}>{loading?"Processing…":"Preview & Validate"}</button></section>
 {error&&<p className="error page-message">{error}</p>}{message&&<p className="success page-message">{message}</p>}
 {preview&&<><section className="metric-grid"><article className="metric"><span>Rows parsed</span><strong>{preview.rowsParsed}</strong><small>{preview.worksheet}</small></article><article className="metric"><span>Valid</span><strong>{preview.validation.valid_rows}</strong><small>Eligible for commit</small></article><article className="metric"><span>Invalid</span><strong>{preview.validation.invalid_rows}</strong><small>Must be fixed first</small></article><article className="metric"><span>Writes</span><strong>0</strong><small>Preview is non-destructive</small></article></section><section className="workspace-banner"><div><span className="muted">Source workbook</span><h2>{preview.sourceSchoolName||"School name not detected"}</h2><p>Target: {school.name}. Source and target are intentionally separate; review the mapping before commit.</p></div><button className="primary-link" disabled={preview.validation.invalid_rows>0||loading} onClick={()=>void commit()}>Commit validated import</button></section></>}
 </section></main>;
}