"use client";
import Link from "next/link";
import { useState } from "react";

type Result = { total_rows:number; valid_rows:number; invalid_rows:number };
type Preview = { batchId:string; sourceSchoolName:string; worksheet:string; rowsParsed:number; validation:Result; safeMode:boolean; writesPerformed:boolean };

export default function ImportBoard({schoolId,school,years,initialYearId}:{schoolId:string;school:{name:string;code:string};years:{id:string;name:string;is_current:boolean}[];initialYearId:string}){
 const [yearId,setYearId]=useState(initialYearId),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const previewFile=async()=>{if(!file||!yearId)return;setLoading(true);setError("");setMessage("");try{const form=new FormData();form.append("file",file);form.append("schoolId",schoolId);form.append("academicYearId",yearId);const r=await fetch("/api/import",{method:"POST",body:form});const b=await r.json();if(!r.ok)throw new Error(b.error||"Import preview failed");setPreview(b.data);setMessage("Workbook staged and validated. No student, guardian, or enrollment records were written.");}catch(e){setError(e instanceof Error?e.message:"Import preview failed")}finally{setLoading(false)}};
 const commit=async()=>{if(!preview||preview.validation.invalid_rows>0)return;setLoading(true);setError("");try{const r=await fetch("/api/gateway",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"data.import.commit",payload:{schoolId,batchId:preview.batchId}})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Import commit failed");setMessage("Import committed: "+JSON.stringify(b.data));}catch(e){setError(e instanceof Error?e.message:"Import commit failed")}finally{setLoading(false)}};
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">E</span><span>EduFlow AI</span></div><p className="sidebar-label">Data</p><nav className="side-nav"><Link href="/">Overview</Link>
<Link href={`/analytics?schoolId=${schoolId}`}>Analytics</Link>
<Link href={`/students?schoolId=${schoolId}`}>Students</Link>
<Link href={`/academic?schoolId=${schoolId}`}>Academic</Link>
<Link href={`/attendance?schoolId=${schoolId}`}>Attendance</Link>
<Link href={`/exams?schoolId=${schoolId}`}>Exams</Link>
<Link href={`/finance?schoolId=${schoolId}`}>Finance</Link>
<Link href={`/hr?schoolId=${schoolId}`}>Staff & HR</Link>
<Link href={`/communication?schoolId=${schoolId}`}>Communication</Link>
<Link href={`/notifications?schoolId=${schoolId}`}>Notifications</Link>
<Link href={`/parent?schoolId=${schoolId}`}>Parent Portal</Link>
<Link className="active" href={`/import?schoolId=${schoolId}`}>Data Import</Link>
<Link href={`/ai?schoolId=${schoolId}`}>AI Assistant</Link>
<Link href="/school/setup">School setup</Link></nav><div className="sidebar-footer"><strong>{school.name}</strong><span>{school.code}</span></div></aside><section className="dashboard"><header className="topbar"><div><p className="eyebrow">V13 · Safe Data Import</p><h1>Production data migration</h1></div></header><section className="workspace-banner"><div><span className="muted">Two-step safety gate</span><h2>Upload → validate → explicitly commit</h2><p>Imports never write student data during preview. Invalid rows block commit.</p></div><div className="workspace-badge">RBAC + RLS + audit</div></section><section className="student-toolbar"><select aria-label="Academic year" value={yearId} onChange={e=>setYearId(e.target.value)}>{years.map(y=><option key={y.id} value={y.id}>{y.name}{y.is_current?" · Current":""}</option>)}</select><input aria-label="Workbook" type="file" accept=".xlsx,.xlsm" onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null)}}/><button className="primary-link" disabled={!file||!yearId||loading} onClick={()=>void previewFile()}>{loading?"Processing…":"Preview & Validate"}</button></section>{error&&<p className="error page-message">{error}</p>}{message&&<p className="success page-message">{message}</p>}{preview&&<><section className="metric-grid"><article className="metric"><span>Rows parsed</span><strong>{preview.rowsParsed}</strong><small>{preview.worksheet}</small></article><article className="metric"><span>Valid</span><strong>{preview.validation.valid_rows}</strong><small>Eligible for commit</small></article><article className="metric"><span>Invalid</span><strong>{preview.validation.invalid_rows}</strong><small>Must be fixed first</small></article><article className="metric"><span>Writes</span><strong>0</strong><small>Preview is non-destructive</small></article></section><section className="workspace-banner"><div><span className="muted">Source workbook</span><h2>{preview.sourceSchoolName || "School name not detected"}</h2><p>Target: {school.name}. Source and target are intentionally separate; review the mapping before commit.</p></div><button className="primary-link" disabled={preview.validation.invalid_rows>0||loading} onClick={()=>void commit()}>Commit validated import</button></section></>}</section></main>;
}